import {
    LayoutDashboard,
    Users,
    MapPin,
    Calendar,
    Settings,
    FileText,
    BarChart3,
    Shield,
    CalendarCheck,
    Wallet,
    Bell,
    MessageSquareQuote,
    Headphones,
    Megaphone,
    Wrench,
    Clock,
    MessageSquare,
    Sparkles,
    BrainCircuit,
    Bot,
} from 'lucide-react';
import { UserRole } from '@/types/auth.types';

export const ROLE_MENUS = {
    [UserRole.ADMIN]: [
        { label: 'Dashboard', icon: LayoutDashboard, href: '/admin/dashboard' },
        { label: 'Users', icon: Users, href: '/admin/users' },
        { label: 'Venues', icon: MapPin, href: '/admin/venues' },
        { label: 'Bookings', icon: Calendar, href: '/admin/bookings' },
        { label: 'Finance', icon: Wallet, href: '/admin/finance' },
        { label: 'AI Assistant', icon: Sparkles, href: '/admin/ai-assistant' },
        { label: 'AI System', icon: BrainCircuit, href: '/admin/ai-system' },
        { label: 'Promotions', icon: Shield, href: '/admin/promotions' },
        { label: 'Content', icon: FileText, href: '/admin/content' },
        { label: 'Reviews', icon: MessageSquareQuote, href: '/admin/reviews' },
        { label: 'Notifications', icon: Bell, href: '/admin/notifications' },
        { label: 'Reports', icon: BarChart3, href: '/admin/reports' },
        { label: 'Moderation', icon: Shield, href: '/admin/moderation' },
        { label: 'Roles', icon: Shield, href: '/admin/roles' },
        { label: 'Chat', icon: MessageSquare, href: '/admin/messages' },
        { label: 'Settings', icon: Settings, href: '/admin/settings' },
    ],
    [UserRole.OWNER]: [
        { label: 'Dashboard', icon: LayoutDashboard, href: '/owner/dashboard' },
        { label: 'My Venues', icon: MapPin, href: '/owner/venues' },
        { label: 'Bookings', icon: Calendar, href: '/owner/bookings' },
        { label: 'Revenue', icon: Wallet, href: '/owner/revenue' },
        { label: 'AI Assistant', icon: Sparkles, href: '/owner/ai-assistant' },
        { label: 'AI Chatbot', icon: Bot, href: '/owner/ai-chatbot' },
        { label: 'Staff', icon: Users, href: '/owner/staff' },
        { label: 'Promotions', icon: Shield, href: '/owner/promotions' },
        { label: 'Analytics', icon: BarChart3, href: '/owner/analytics' },
        { label: 'Chat', icon: MessageSquare, href: '/owner/messages' },
        { label: 'Settings', icon: Settings, href: '/owner/settings' },
    ],
    [UserRole.STAFF]: [
        { label: 'Support', icon: Headphones, href: '/staff/support' },
        { label: 'Marketing', icon: Megaphone, href: '/staff/marketing' },
        { label: 'Technical', icon: Wrench, href: '/staff/technical' },
        { label: 'Finance', icon: Wallet, href: '/staff/finance' },
        { label: 'Moderation', icon: Shield, href: '/staff/moderation' },
        { label: 'Chat', icon: MessageSquare, href: '/staff/messages' },
    ],
    [UserRole.VENUE_STAFF]: [
        { label: 'Dashboard', icon: LayoutDashboard, href: '/venue-staff/dashboard' },
        { label: 'AI Helper', icon: Bot, href: '/venue-staff/ai-helper' },
        { label: 'Bookings', icon: Calendar, href: '/venue-staff/bookings' },
        { label: 'My Venues', icon: MapPin, href: '/venue-staff/venues' },
        { label: 'Schedule', icon: Clock, href: '/venue-staff/schedule' },
        { label: 'Messages', icon: MessageSquare, href: '/venue-staff/messages' },
        { label: 'Reports', icon: BarChart3, href: '/venue-staff/reports' },
    ],
    [UserRole.CUSTOMER]: [
        { label: 'Home', icon: LayoutDashboard, href: '/' },
        { label: 'AI Assistant', icon: Sparkles, href: '/ai-assistant' },
    ]
};
