export const MOCK_USERS = [
    {
        email: 'superadmin@datsan247.vn',
        password: 'password123',
        fullName: 'Super Admin',
        role: 'super_admin',
        redirect: '/admin/dashboard',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    },
    {
        email: 'admin@datsan247.vn',
        password: 'password123',
        fullName: 'Platform Admin',
        role: 'admin',
        redirect: '/admin/dashboard',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=platform',
    },
    {
        email: 'staff@datsan247.vn',
        password: 'password123',
        fullName: 'Platform Staff',
        role: 'staff',
        redirect: '/staff/dashboard',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=platformstaff',
    },
    {
        email: 'owner@datsan247.vn',
        password: 'password123',
        fullName: 'Venue Owner',
        role: 'owner',
        redirect: '/owner/dashboard',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=owner',
    },
    {
        email: 'venuestaff@datsan247.vn',
        password: 'password123',
        fullName: 'Venue Staff',
        role: 'venue_staff',
        redirect: '/venue-staff/dashboard',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=venuestaff',
    },
    {
        email: 'customer@gmail.com',
        password: 'password123',
        fullName: 'Phạm Đức Lợi',
        role: 'customer',
        redirect: '/',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=customer',
    },
];
